name: New Workflow

# Controls when the action will run.
on:
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  new:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: new
        run: echo "new code"
