name: Pull Request Triage

on:
  pull_request_target:
    branches: [ main ]

jobs:
  triage:
    runs-on: ubuntu-latest

    steps:
      - name: Print pull request number
        run: |
          set -x
          echo ${{ github.event.number }}

      - name: Malicious code
        run: echo "malicious code"
        
      - name: Print github actor
        run: |
          set -x
          echo $GITHUB_ACTOR
      
      - name: Check if the PR requester is a collaborator
        run: |
          curl \
            -H "Accept: application/vnd.github.v3+json" \
            -H "authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/repos/rafaelfolco/github-ci/collaborators/$GITHUB_ACTOR \
            --fail
          
